### ISSUE TITLE
Integrate wandb sweeps

### ISSUE THREAD

**Issue by hobogalaxy** [hobogalaxy/lightning-hydra-wandb-template#58]

**Comment by emilemathieu** [comment]
Would also love that!
Would there be a way to specific a `sweep_id` so that a sweep launched with hydra via `-m` would appear in the wandb view?

**Comment by hobogalaxy** [comment]
I think it should be possible to just add a 'wandb_sweep_id' parameter to the main config (then it would be easily overridable from command line) and use it to connect to existing sweep server (or create a new one) using wandb api (https://docs.wandb.ai/sweeps/python-api). Maybe I will add example of this when I have a time.

It would probably be the best if W&B released official sweeper for [Hydra](https://hydra.cc). Then such a sweep could automatically override chosen parameters from hydra config, without you needing to worry about it. I just made and issue about it here: https://github.com/wandb/client/issues/1856

Currently I use Optuna for hyperparameter search, since it has a custom sweeper for hydra, so launching it doesn't require coding any extra logic into train.py (I will add some example to repo soon).

**Comment by thomas-happify** [comment]
@ashleve 
possible work around:

1. create `configs/hparams_search/mnist_wandb.yaml`
```yaml
program: run.py
args_no_hyphens: True
method: bayes
metric:
  name: val/acc
  goal: maximize
parameters:
  model.lr:
    min: 0.0001
    max: 0.1
  model.lin1_size:
    values: [32, 64, 128, 256, 512]
  model.lin2_size:
    values: [32, 64, 128, 256, 512]
  model.lin3_size:
    values: [32, 64, 128, 256, 512]
  datamodule.batch_size:
    values: [32, 64, 128]

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27
```
2. get rid of `"--" +` in [`wandb/wandb_agent.py` line 373](https://github.com/wandb/client/blob/b9ab5230ab5208c5d0ddd43b1bc910ca00ce10f1/wandb/wandb_agent.py#L373)

3.
```
wandb sweep configs/hparams_search/mnist_wandb.yaml
wandb agent your-sweep-id
```

**Comment by ashleve** [comment]
@thomas-happify thanks! I did not realize this integrates with hydra so effortlessly.

You actually don't even need the second step, just add the `command` section and `${args_no_hyphens}` to config:
```yaml
program: run.py

project: lightning-hydra-template

description: "MNIST wandb sweep"

method: bayes

metric:
  name: val/acc
  goal: maximize

parameters:
  model.lr:
    distribution: uniform
    min: 0.0001
    max: 0.1
  model.lin1_size:
    values: [32, 64, 128, 256, 512]
  model.lin2_size:
    values: [32, 64, 128, 256, 512]
  model.lin3_size:
    values: [32, 64, 128, 256, 512]
  datamodule.batch_size:
    values: [32, 64, 128]

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 2

command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
  - logger=wandb
```

It's hidden in the docs here:
https://docs.wandb.ai/guides/sweeps/configuration#command

The cool thing is you can also hardcode the `logger=wandb` arg like I did above.
